server:
  port: 8082
spring:
  application:
    name: order_verify
  sleuth:
    sampler:
      probability: 1.0
  datasource:
    url: jdbc:mysql://localhost:3306/test_springboot_stream?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: Welcome1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  security:
    user:
      name: client1
      password: password
      roles: USER
  redis:
    host: localhost
    port: 6379
grpc:
  port: 50051
  security:
    cert-chain: file:../order/ssl/server.crt
    private-key: file:../order/ssl/server.pem

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

